const cod_packages = [
    {
        id: 1,
        name: '1 window - 1 day (free-trial)',
        vip: 'VIP',
        price: '0.00$',
        isReduced: true,
        reduced_price: '0.00$',
        price_vi: '0 đ',
        reduced_price_vi: '0 đ',
    },
    {
        id: 2,
        name: '1 window - 7 days',
        vip: 'VIP',
        price: '5.00$',
        isReduced: true,
        reduced_price: '4.00$',
        price_vi: '100.000 đ',
        reduced_price_vi: '92.000 đ',
    },
    {
        id: 3,
        name: '1 window - 30 days',
        vip: 'VIP',
        price: '15.00$',
        isReduced: true,
        reduced_price: '10.00$',
        price_vi: '300.000 đ',
        reduced_price_vi: '230.000 đ',
    },
    {
        id: 4,
        name: '3 windows - 7 days',
        vip: 'VIP',
        price: '7.50$',
        isReduced: true,
        reduced_price: '6.00$',
        price_vi: '150.000 đ',
        reduced_price_vi: '138.000 đ',
    },
    {
        id: 5,
        name: '3 windows - 30 days',
        vip: 'VIP',
        price: '20.00$',
        isReduced: true,
        reduced_price: '15.00$',
        price_vi: '400.000 đ',
        reduced_price_vi: '345.000 đ',
    },
    {
        id: 6,
        name: '6 windows - 7 days',
        vip: 'VIP',
        price: '12.50$',
        isReduced: true,
        reduced_price: '10.00$',
        price_vi: '250.000 đ',
        reduced_price_vi: '230.000 đ',
    },
    {
        id: 7,
        name: '6 windows - 30 days',
        vip: 'VIP',
        price: '30.00$',
        isReduced: true,
        reduced_price: '25.00$',
        price_vi: '600.000 đ',
        reduced_price_vi: '575.000 đ',
    },
    {
        id: 8,
        name: '12 windows - 7 days',
        vip: 'VIP',
        price: '20.00$',
        isReduced: true,
        reduced_price: '15.00$',
        price_vi: '400.000 đ',
        reduced_price_vi: '345.000 đ',
    },
    {
        id: 9,
        name: '12 windows - 30 days',
        vip: 'VIP',
        price: '45.00$',
        isReduced: true,
        reduced_price: '38.00$',
        price_vi: '900.000 đ',
        reduced_price_vi: '874.000 đ',
    },
    {
        id: 10,
        name: '24 windows - 7 days',
        vip: 'VIP',
        price: '32.50$',
        isReduced: true,
        reduced_price: '24.00$',
        price_vi: '650.000 đ',
        reduced_price_vi: '552.000 đ',
    },
    {
        id: 11,
        name: '24 windows - 30 days',
        vip: 'VIP',
        price: '70.00$',
        isReduced: true,
        reduced_price: '60.00$',
        price_vi: '1.400.000 đ',
        reduced_price_vi: '1.380.000 đ',
    },
    {
        id: 12,
        name: '36 windows - 7 days',
        vip: 'VIP',
        price: '50.00$',
        isReduced: true,
        reduced_price: '36.00$',
        price_vi: '1.000.000 đ',
        reduced_price_vi: '828.000 đ',
    },
    {
        id: 13,
        name: '36 windows - 30 days',
        vip: 'VIP',
        price: '110.00$',
        isReduced: true,
        reduced_price: '90.00$',
        price_vi: '2.200.000 đ',
        reduced_price_vi: '2.070.000 đ',
    },
    {
        id: 14,
        name: '48 windows - 7 days',
        vip: 'VIP',
        price: '60.00$',
        isReduced: true,
        reduced_price: '44.00$',
        price_vi: '1.200.000 đ',
        reduced_price_vi: '1.012.000 đ',
    },
    {
        id: 15,
        name: '48 windows - 30 days',
        vip: 'VIP',
        price: '140.00$',
        isReduced: true,
        reduced_price: '110.00$',
        price_vi: '2.800.000 đ',
        reduced_price_vi: '2.530.000 đ',
    },
]

export default cod_packages;
