const cod_packages = [
    {
        id: 1,
        name: '1 window - 1 day (free-trial)',
        vip: 'VIP',
        price: '0.00$',
        isReduced: false,
        reduced_price: '0.00$',
    },
    {
        id: 2,
        name: '1 window - 7 days',
        vip: 'VIP',
        price: '5.00$',
        isReduced: false,
        reduced_price: '4.00$',
    },
    {
        id: 3,
        name: '1 window - 30 days',
        vip: 'VIP',
        price: '15.00$',
        isReduced: false,
        reduced_price: '10.00$',
    },
    {
        id: 4,
        name: '3 windows - 7 days',
        vip: 'VIP',
        price: '7.50$',
        isReduced: false,
        reduced_price: '6.00$',
    },
    {
        id: 5,
        name: '3 windows - 30 days',
        vip: 'VIP',
        price: '20.00$',
        isReduced: false,
        reduced_price: '15.00$',
    },
    {
        id: 6,
        name: '6 windows - 7 days',
        vip: 'VIP',
        price: '12.50$',
        isReduced: false,
        reduced_price: '10.00$',
    },
    {
        id: 7,
        name: '6 windows - 30 days',
        vip: 'VIP',
        price: '30.00$',
        isReduced: false,
        reduced_price: '25.00$',
    },
    {
        id: 8,
        name: '12 windows - 7 days',
        vip: 'VIP',
        price: '20.00$',
        isReduced: false,
        reduced_price: '15.00$',
    },
    {
        id: 9,
        name: '12 windows - 30 days',
        vip: 'VIP',
        price: '45.00$',
        isReduced: false,
        reduced_price: '38.00$',
    },
    {
        id: 10,
        name: '24 windows - 7 days',
        vip: 'VIP',
        price: '32.50$',
        isReduced: false,
        reduced_price: '24.00$',
    },
    {
        id: 11,
        name: '24 windows - 30 days',
        vip: 'VIP',
        price: '70.00$',
        isReduced: false,
        reduced_price: '60.00$',
    },
    {
        id: 12,
        name: '36 windows - 7 days',
        vip: 'VIP',
        price: '50.00$',
        isReduced: false,
        reduced_price: '36.00$',
    },
    {
        id: 13,
        name: '36 windows - 30 days',
        vip: 'VIP',
        price: '110.00$',
        isReduced: false,
        reduced_price: '90.00$',
    },
    {
        id: 14,
        name: '48 windows - 7 days',
        vip: 'VIP',
        price: '60.00$',
        isReduced: false,
        reduced_price: '44.00$',
    },
    {
        id: 15,
        name: '48 windows - 30 days',
        vip: 'VIP',
        price: '140.00$',
        isReduced: false,
        reduced_price: '110.00$',
    },
]

export default cod_packages;
