const rok_packages = [
    {
        id: 1,
        name: '1 window - 1 day (free-trial)',
        vip: 'VIP-2',
        price: '0.00$',
        isReduced: false,
        reduced_price: '0.00$',
    },
    {
        id: 2,
        name: '1 window - 7 days',
        vip: 'VIP',
        price: '5.00$',
        isReduced: true,
        reduced_price: '4.00$',
    }, 
    {
        id: 3,
        name: '1 window - 7 days',
        vip: 'VIP-2',
        price: '10.00$',
        isReduced: true,
        reduced_price: '8.00$',
    },
    {
        id: 4,
        name: '1 window - 30 days',
        vip: 'VIP',
        price: '10.00$',
        isReduced: true,
        reduced_price: '15.00$',
    }, 
    {
        id: 5,
        name: '1 window - 30 days',
        vip: 'VIP-2',
        price: '28.00$',
        isReduced: true,
        reduced_price: '20.00$',
    },
    {
        id: 6,
        name: '3 window - 7 days',
        vip: 'VIP',
        price: '7.50$',
        isReduced: true,
        reduced_price: '6.00$',
    },
    {
        id: 7,
        name: '3 window - 7 days',
        vip: 'VIP-2',
        price: '12.50$',
        isReduced: true,
        reduced_price: '10.00$',
    },
    {
        id: 8,
        name: '3 window - 30 days',
        vip: 'VIP',
        price: '20.00$',
        isReduced: true,
        reduced_price: '15.00$',
    },
    {
        id: 9,
        name: '3 window - 30 days',
        vip: 'VIP-2',
        price: '40.00$',
        isReduced: true,
        reduced_price: '25.00$',
    },
    {
        id: 10,
        name: '6 window - 7 days',
        vip: 'VIP',
        price: '12.50$',
        isReduced: true,
        reduced_price: '10.00$',
    },
    {
        id: 11,
        name: '6 window - 7 days',
        vip: 'VIP-2',
        price: '20.00$',
        isReduced: true,
        reduced_price: '15.00$',
    },
    {
        id: 12,
        name: '6 window - 30 days',
        vip: 'VIP',
        price: '30.00$',
        isReduced: true,
        reduced_price: '25.00$',
    },
    {
        id: 13,
        name: '6 window - 30 days',
        vip: 'VIP-2',
        price: '60.00$',
        isReduced: true,
        reduced_price: '38.00$',
    },
    {
        id: 14,
        name: '12 window - 7 days',
        vip: 'VIP',
        price: '20.00$',
        isReduced: true,
        reduced_price: '15.00$',
    },
    {
        id: 15,
        name: '12 window - 7 days',
        vip: 'VIP-2',
        price: '32.50$',
        isReduced: true,
        reduced_price: '24.00$',
    },
    {
        id: 16,
        name: '12 window - 30 days',
        vip: 'VIP',
        price: '45.00$',
        isReduced: true,
        reduced_price: '38.00$',
    },
    {
        id: 17,
        name: '12 window - 30 days',
        vip: 'VIP-2',
        price: '90.00$',
        isReduced: true,
        reduced_price: '60.00$',
    },
    {
        id: 18,
        name: '24 window - 7 days',
        vip: 'VIP',
        price: '32.50$',
        isReduced: true,
        reduced_price: '24.00$',
    },
    {
        id: 19,
        name: '24 window - 7 days',
        vip: 'VIP-2',
        price: '55.00$',
        isReduced: true,
        reduced_price: '36.00$',
    },
    {
        id: 20,
        name: '24 window - 30 days',
        vip: 'VIP',
        price: '70.00$',
        isReduced: true,
        reduced_price: '60.00$',
    },
    {
        id: 21,
        name: '24 window - 30 days',
        vip: 'VIP-2',
        price: '140.00$',
        isReduced: true,
        reduced_price: '90.00$',
    },
    {
        id: 22,
        name: '36 window - 7 days',
        vip: 'VIP',
        price: '50.00$',
        isReduced: true,
        reduced_price: '36.00$',
    },
    {
        id: 23,
        name: '36 window - 7 days',
        vip: 'VIP-2',
        price: '60.00$',
        isReduced: true,
        reduced_price: '44.00$',
    },
    {
        id: 24,
        name: '36 window - 30 days',
        vip: 'VIP',
        price: '110.00$',
        isReduced: true,
        reduced_price: '90.00$',
    },
    {
        id: 25,
        name: '36 window - 30 days',
        vip: 'VIP-2',
        price: '140.00$',
        isReduced: true,
        reduced_price: '110.00$',
    },
    {
        id: 26,
        name: '48 window - 7 days',
        vip: 'VIP',
        price: '60.00$',
        isReduced: true,
        reduced_price: '44.00$',
    },
    {
        id: 27,
        name: '48 window - 7 days',
        vip: 'VIP-2',
        price: '70.00$',
        isReduced: true,
        reduced_price: '50.00$',
    },
    {
        id: 28,
        name: '48 window - 30 days',
        vip: 'VIP',
        price: '110.00$',
        isReduced: true,
        reduced_price: '140.00$',
    },
    {
        id: 29,
        name: '48 window - 30 days',
        vip: 'VIP-2',
        price: '160.00$',
        isReduced: true,
        reduced_price: '125.00$',
    },
]

export default rok_packages;
